env:
  global:
    - CC_TEST_REPORTER_ID=541ae4ee0ae033e77ad49e9ca8d7f7fd49d7ffdb17e060fe2d614d3c3fc881e1

language: php

php:
  - '7.1'

install:
  - composer install --no-interaction --prefer-dist

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - composer run test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
